language: node_js
services:
  - mongodb
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
before_install:
  - npm install -g grunt-cli
  - npm install grunt-ghost
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.0.2
  - export PATH=$PATH:`pwd`/bin
  - cd -
before_script:
  - mongo test --eval 'db.createCollection("sprint");'
  - mongo test --eval 'db.createCollection("story");'
  - mongo test --eval 'db.createCollection("task");'
  - "mongo test --eval 'db.task.ensureIndex({story_id: 1, priority: 1}, {unique: true});'"
  - "mongo test --eval 'db.story.ensureIndex({sprint_id: 1, priority: 1}, {unique: true});'"
  - phantomjs --version
  - casperjs --version
